version: '3.8'

services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: retrostream-frontend
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Development version with volume mounts for hot reload
  frontend-dev:
    image: node:18-alpine
    container_name: retrostream-frontend-dev
    working_dir: /app
    command: npm run dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    environment:
      - HOST=0.0.0.0
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    profiles: ["dev"]