version: '3.8'

services:
  retrostream:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: retrostream-app
    ports:
      - "8080:8080"   # Backend API
      - "3000:3000"   # Frontend
    environment:
      - DISPLAY=:99
      - RESOLUTION=1280x720
      - RUST_LOG=info
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development version with hot reload
  retrostream-dev:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: retrostream-dev
    ports:
      - "8081:8080"   # Backend API (different port)
      - "3001:3000"   # Frontend (different port)
    environment:
      - DISPLAY=:99
      - RESOLUTION=1920x1080
      - RUST_LOG=debug
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./backend/src:/app/backend/src:ro
      - ./frontend/src:/app/frontend/src:ro
    command: ["dev"]
    restart: unless-stopped
    profiles: ["dev"]
